# This is a basic workflow to help you get started with Actions
name: Test ETL

# Controls when the workflow will run
on:
  # Triggers the workflow on push request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
      
      # - name: Install OpenVPN
      #   run: |
      #     sudo apt update
      #     sudo apt install -y openvpn openvpn-systemd-resolved

      # - name: Connect to VPN
      #   uses: "kota65535/github-openvpn-connect-action@v2"
      #   with:
      #     config_file: .github/workflows/vpn/otsietladm__ssl_vpn_config.ovpn
      #     username: ${{ secrets.OVPN_USERNAME }}
      #     password: ${{ secrets.OVPN_PASSWORD }}
      #     client_key: ${{ secrets.OVPN_CLIENTKEY }}

      - name: Copy files via SSH key
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.TEST_HOST }}
          port: ${{ secrets.TEST_PORT }}
          username: ${{ secrets.TEST_USERNAME }}
          key: ${{ secrets.TEST_KEY }}
          source: "./"
          target: "/home/ec2-user/"

      - name: Execute install.sh via SSH key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.TEST_HOST }}
          port: ${{ secrets.TEST_PORT }}
          username: ${{ secrets.TEST_USERNAME }}
          key: ${{ secrets.TEST_KEY }}
          script: |
            cd /home/ec2-user/
            git clean -fd
            sh install.sh

      - name: Create ENV files via SSH key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.TEST_HOST }}
          port: ${{ secrets.TEST_PORT }}
          username: ${{ secrets.TEST_USERNAME }}
          key: ${{ secrets.TEST_KEY }}
          script: echo "${{ secrets.UTILS_ENV }}" > "/home/ec2-user/.env"

      - name: Execute deploy.sh via SSH key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.TEST_HOST }}
          port: ${{ secrets.TEST_PORT }}
          username: ${{ secrets.TEST_USERNAME }}
          key: ${{ secrets.TEST_KEY }}
          script: sh /home/ec2-user/deploy.sh